[package]
name = "malwaredb-client"
version = "0.0.1"
edition = "2021"

[dependencies]
# Internal dependencies
malwaredb-api = { workspace = true }
malwaredb-types = { workspace = true }

# External dependencies
anyhow = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true }
dialoguer = { workspace = true }
hex = { workspace = true }
home = { workspace = true }
malwaredb-lzjd = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
ssdeep = { workspace = true }
tlsh-fixed = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
walkdir = { workspace = true }
zeroize = { workspace = true }
zip = { workspace = true }

[[bin]]
name = "mdb_client"
path = "src/main.rs"