[package]
name = "malwaredb_client"
version = "0.1.0"
edition = "2021"

[dependencies]
# Internal dependencies
api = { workspace = true }

# External dependencies
anyhow = { workspace = true }
clap = { workspace = true }
dialoguer = { workspace = true }
home = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
zeroize = { workspace = true }

[[bin]]
name = "mdb_client"
path = "src/main.rs"