[package]
name = "malwaredb-client"
version = "0.0.10-dev"
edition = "2021"
license = "Apache-2.0"
authors = ["Richard Zak <richard.j.zak@gmail.com>"]
description = "Client application for MalwareDB."
homepage = "https://malwaredb.net/"
repository = "https://github.com/malwaredb/malwaredb-rs"
build = "build.rs"
keywords = ["cybersecurity", "malware"]

[features]
default = []
zlibng = ["flate2/zlib-ng", "zip/deflate-zlib-ng"]

[dependencies]
# Internal dependencies
malwaredb-api = { workspace = true }
malwaredb-types = { workspace = true, features = ["officexml", "pe32"] }

# External dependencies
anyhow = { workspace = true, features = ["std"] }
base64 = { workspace = true, features = ["std"] }
clap = { workspace = true, features = ["color", "derive", "help", "suggestions"] }
dialoguer = { workspace = true, features = ["password"] }
flate2 = { workspace = true }
fuzzyhash = { workspace = true }
hex = { workspace = true }
home = { workspace = true }
malwaredb-lzjd = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["default", "std"] }
serde_json = { workspace = true, features = ["std"] }
sha2 = { workspace = true }
tlsh-fixed = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
toml = { workspace = true, features = ["display", "parse"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt", "json"] }
walkdir = { workspace = true }
zeroize = { workspace = true, features = ["derive"] }
zip = { workspace = true, features = ["aes-crypto", "deflate"] }

[target.'cfg(windows)'.build-dependencies]
winresource = { workspace = true }

[build-dependencies]
vergen = { workspace = true, features = ["build", "git", "gitcl"] }

[package.metadata.deb]
license-file = ["../LICENSE", "0"]
features = ["zlibng"]
recommends = "malwaredb"
section = "databases"

[package.metadata.winresource]
OriginalFilename = "MDB_CLIENT.EXE"
LegalCopyright = "Copyright © 2023-2024, MalwareDB Developers"

[[bin]]
name = "mdb_client"
path = "src/main.rs"
