[package]
name = "malwaredb-client"
version = "0.0.3"
edition = "2021"
license = "Apache-2.0"
authors = ["Richard Zak <richard.j.zak@gmail.com>"]
description = "Client application for MalwareDB."
homepage = "https://malwaredb.net/"
repository = "https://github.com/malwaredb/malwaredb-rs"

[dependencies]
# Internal dependencies
malwaredb-api = { workspace = true }
malwaredb-types = { workspace = true }

# External dependencies
anyhow = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true }
dialoguer = { workspace = true }
fuzzyhash = { workspace = true }
hex = { workspace = true }
home = { workspace = true }
malwaredb-lzjd = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tlsh-fixed = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
walkdir = { workspace = true }
zeroize = { workspace = true }
zip = { workspace = true }

[[bin]]
name = "mdb_client"
path = "src/main.rs"