[package]
name = "malwaredb-client"
version = "0.0.8-dev"
edition = "2021"
license = "Apache-2.0"
authors = ["Richard Zak <richard.j.zak@gmail.com>"]
description = "Client application for MalwareDB."
homepage = "https://malwaredb.net/"
repository = "https://github.com/malwaredb/malwaredb-rs"
build = "build.rs"
keywords = ["cybersecurity", "malware"]

[features]
default = []
zlibng = ["flate2/zlib-ng"]

[dependencies]
# Internal dependencies
malwaredb-api = { workspace = true }
malwaredb-types = { workspace = true, features = ["officexml", "pe32"], default-features = false }

# External dependencies
anyhow = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true }
dialoguer = { workspace = true }
flate2 = { workspace = true }
fuzzyhash = { workspace = true }
hex = { workspace = true }
home = { workspace = true }
malwaredb-lzjd = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tlsh-fixed = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
toml = { workspace = true }
walkdir = { workspace = true }
zeroize = { workspace = true }
zip = { workspace = true }

[target.'cfg(windows)'.build-dependencies]
winresource = { workspace = true }

[build-dependencies]
vergen = { workspace = true }

[package.metadata.deb]
license-file = ["../LICENSE", "0"]
features = ["zlibng"]
recommends = "malwaredb"
section = "databases"

[package.metadata.winresource]
OriginalFilename = "MDB_CLIENT.EXE"
LegalCopyright = "Copyright © 2023-2024, MalwareDB Developers"

[[bin]]
name = "mdb_client"
path = "src/main.rs"
