[package]
name = "exec"
version = "0.1.0"
edition = "2021"

[features]
default = ["elf", "macho", "pe32"]
elf = []
macho = []
pe32 = ["dep:chrono", "dep:flagset"]
pef = ["dep:chrono"]

[dependencies]
# Internal
types = { workspace = true }

# External
anyhow = { workspace = true }
chrono = { workspace = true, optional = true }
flagset = { workspace = true, optional = true }

[dev-dependencies]
rstest = { workspace = true }