[package]
name = "exec"
version = "0.1.0"
edition = "2021"

[features]
default = ["elf", "macho", "pe32"]
elf = []
macho = []
pe32 = []

[dependencies]
# Internal
types = { workspace = true }

# External
anyhow = { workspace = true }
