[package]
name = "exec_parsing"
version = "0.1.0"
edition = "2021"

[features]
default = ["elf", "macho", "pe32"]
elf = []
macho = []
pe32 = []

[dependencies]
anyhow = { workspace = true }

[profile.release]
lto = true
