[package]
name = "malwaredb"
version = "0.1.0"
edition = "2021"

[features]
default = []
sqlite = ["dep:rusqlite"]

[dependencies]
api = { workspace = true }
types = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
confargs = { workspace = true }
rusqlite = { workspace = true, optional = true }

[dev-dependencies]
rusqlite = { workspace = true }

[workspace.dependencies]
# Internal dependencies
api = { path = "crates/api", version = "0.1.0" }
server = { path = "crates/server", version = "0.1.0" }
types = { path = "crates/types", version = "0.1.0" }

# External dependencies
anyhow = { version = "1.0", features = ["std"] }
chrono = { version = "0.4.24", features = ["clock"], default-features = false }
clap = { version = "4.1.13", features = ["derive", "std"], default-features = false }
confargs = { version = "^0.1.3", default-features = false }
flagset = { version = "0.4.3", default-features = false }
fuzzyhash = { version = "0.2.2", default-features = false }
hex = { version = "0.4.3", features = ["alloc"], default-features = false }
md-5 = { version = "0.10.5", default-features = false }
rstest = { version = "0.17.0", default-features = false }
rusqlite = { version = "0.28.0", features = ["bundled"], default-features = false }
tlsh = { version = "0.1.0", default-features = false }

[profile.release]
lto = true

[[bin]]
name = "mdb_client"
path = "client/src/main.rs"

[[bin]]
name = "mdb_server"
path = "src/main.rs"

[workspace]
resolver = "2"
members = [
    'crates/api',
    'crates/types',
    'crates/server',
    'client',
]