[package]
name = "malwaredb"
version = "0.1.0"
edition = "2021"

[dependencies]
exec_parsing = { workspace = true }

[workspace.dependencies]
# Internal dependencies
exec_parsing = { path = "crates/exec_parsing", version = "0.1.0" }

# External dependencies
anyhow = { version = "1.0", features = ["std"] }
fuzzyhash = { version = "0.2.1" }
tlsh = { version = "0.1.0" }

[profile.release]
lto = true

[workspace]
resolver = "2"
members = [
    'crates/exec_parsing'
]