[package]
name = "malwaredb"
version = "0.1.0"
edition = "2021"

[dependencies]
exec = { workspace = true }
types = { workspace = true }

[workspace.dependencies]
# Internal dependencies
exec = { path = "crates/exec", version = "0.1.0" }
types = { path = "crates/types", version = "0.1.0" }

# External dependencies
anyhow = { version = "1.0", features = ["std"] }
chrono = { version = "0.4.19", features = ["clock"], default-features = false }
flagset = { version = "0.4.3", default-features = false }
fuzzyhash = { version = "0.2.1" }
rstest = { version = "0.16", default-features = false }
tlsh = { version = "0.1.0" }

[profile.release]
lto = true

[workspace]
resolver = "2"
members = [
    'crates/exec',
    'crates/types'
]