[package]
name = "malwaredb"
version = "0.0.10-dev"
edition = "2021"
license = "Apache-2.0"
authors = ["Richard Zak <richard.j.zak@gmail.com>"]
description = "MalwareDB does the bookkeeping for malware & goodware datasets, aimed at helping malware researchers and forensic investigators."
homepage = "https://malwaredb.net/"
repository = "https://github.com/malwaredb/malwaredb-rs"
keywords = ["cybersecurity", "malware", "malware-research", "forensics"]
categories = ["database", "data-structures", "parsing"]
build = "build.rs"

[features]
default = []
admin = ["dep:dialoguer", "dep:flate2", "malwaredb-server/admin", "dep:chrono", "dep:walkdir", "dep:zip"]
admin-gui = ["malwaredb-server/admin", "dep:slint", "dep:slint-build", "futures/executor"]
sqlite = ["malwaredb-server/sqlite"]
vt = ["malwaredb-server/vt", "dep:malwaredb-virustotal"]
zlibng = ["malwaredb-server/zlibng"]

[dependencies]
malwaredb-api = { workspace = true }
malwaredb-server = { workspace = true }
malwaredb-types = { workspace = true, features = ["elf", "macho", "office95", "officexml", "pdf", "pe32", "pef", "rtf"] }

anyhow = { workspace = true }
bytesize = { workspace = true }
cart_container = { workspace = true }
chrono = { workspace = true, optional = true }
clap = { workspace = true }
clap_complete = { workspace = true }
dialoguer = { workspace = true, optional = true }
flate2 = { workspace = true, features = ["zlib-ng"], optional = true }
futures = { workspace = true, optional = true }
hex = { workspace = true }
home = { workspace = true }
malwaredb-virustotal = { workspace = true, optional = true }
serde = { workspace = true }
slint = { workspace = true, optional = true }
tokio = { workspace = true, features = ["rt", "macros"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
walkdir = { workspace = true, optional = true }
zip = { workspace = true, optional = true }
zeroize = { workspace = true }

[target.'cfg(not(target_os = "wasi"))'.dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
malwaredb-server = { workspace = true, features = ["sqlite"] }

[build-dependencies]
slint-build = { workspace = true, optional = true }
vergen = { workspace = true }

[target.'cfg(windows)'.build-dependencies]
winresource = { workspace = true }

[package.metadata.deb]
license-file = ["LICENSE", "0"]
depends = "$auto"
features = ["admin", "admin-gui", "sqlite", "vt", "zlibng"]
priority = "optional"
recommends = "postgresql"
section = "databases"

[package.metadata.winresource]
OriginalFilename = "MDB_SERVER.EXE"
LegalCopyright = "Copyright © 2023-2024, MalwareDB Developers"

[workspace.dependencies]
# Internal dependencies
malwaredb-api = { path = "crates/api", version = "0.0.10-dev" }
malwaredb-client = { path = "client", version = "0.0.10-dev" }
malwaredb-server = { path = "crates/server", version = "0.0.10-dev" }
malwaredb-types = { path = "crates/types", version = "0.0.10-dev", default-features = false }

# External dependencies
aes-gcm = { version = "0.10.3", features = ["aes", "alloc", "getrandom", "std"], default-features = false }
anyhow = { version = "1.0", features = ["std"] }
argon2 = { version = "0.5.3", features = ["alloc", "std"], default-features = false }
axum = { version = "0.7.5", features = ["http1", "json", "macros", "tokio"], default-features = false }
axum-macros = { version = "0.4.0", default-features = false }
base64 = { version = "0.22.1", default-features = false }
bytesize = { version = "1.3", features = ["serde"], default-features = false }
cart_container = { version = "0.1.8", default-features = false }
chrono = { version = "0.4.38", features = ["clock", "serde"], default-features = false }
chrono-humanize = { version = "0.2.3", default-features = false }
clap = { version = "4.5", features = ["derive", "help", "std", "usage"], default-features = false }
clap_complete = { version = "4.5", default-features = false }
constcat = { version = "0.5.0", default-features = false }
deadpool-postgres = { version = "0.13.0", features = ["rt_tokio_1"], default-features = false }
dialoguer = { version = "0.11.0", features = ["password"], default-features = false }
flagset = { version = "0.4.5", default-features = false }
flate2 = { version = "1.0.29" }
futures = { version = "0.3.30", default-features = false }
fuzzyhash = { version = "0.2.2", default-features = false }
hex = { version = "0.4.3", features = ["alloc", "std"], default-features = false }
home = { version = "0.5.9", default-features = false }
http = { version = "1.1.0", default-features = false }
http-body-util = { version = "0.1.0", default-features = false }
human-hash = { version = "0.4.0", default-features = false }
humansize = { version = "2.1", default-features = false }
hyper = { version = "1.3.1", features = ["http1", "server"], default-features = false }
magic = { version = "0.16.2", default-features = false }
malwaredb-lzjd = { version = "0.1.2", default-features = false }
malwaredb-virustotal = { version = "0.0.5", default-features = false }
md-5 = { version = "0.10.6", default-features = false }
pdf = { version = "0.9.0", features = ["cache"], default-features = false }
postgres = { version = "0.19.7", features = ["array-impls", "with-chrono-0_4"], default-features = false }
rc4 = { version = "0.1", features = ["std", "zeroize"] }
reqwest = { version = "0.12.4", features = ["blocking", "json", "deflate", "gzip"], default-features = false }
rstest = { version = "0.19.0", default-features = false }
rusqlite = { version = "0.31.0", features = ["bundled"], default-features = false }
serde = { version = "1.0", features = ["derive", "std"], default-features = false }
serde_json = { version = "1.0", features = ["alloc"], default-features = false }
sha1 = { version = "0.10.6", features = ["std"], default-features = false }
sha2 = { version = "0.10.8", features = ["std"], default-features = false }
slint = { version = "1.5" }
slint-build = { version = "1.5" }
tempfile = { version = "3.10", default-features = false }
tlsh-fixed = { version = "0.1.1", default-features = false }
tokio = { version = "1.37", features = ["rt", "macros"], default-features = false }
toml = { version = "0.8.12", features = ["display", "parse"], default-features = false }
tower = { version = "0.4.13", features = ["util"], default-features = false }
tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json", "fmt"], default-features = false }
uuid = { version = "1.8", features = ["v4", "macro-diagnostics"], default-features = false }
vcpkg = { version = "0.2.15", default-features = false }
vergen = { version = "8.3", features = ["build", "git", "gitcl"] }
walkdir = { version = "2.5", default-features = false }
winresource = { version = "0.1.17", default-features = false }
xor-utils = { version = "0.6.0", default-features = false }
zip = { version = "1.1.3", features = ["aes-crypto", "deflate"], default-features = false }
zeroize = { version = "1.7.0", features = ["alloc", "derive"], default-features = false }

[profile.release]
codegen-units = 1
lto = true
strip = "symbols"

[[bin]]
name = "mdb_server"
path = "src/main.rs"

[workspace]
resolver = "2"
members = [
    'crates/api',
    'crates/server',
    'crates/types',
    'client',
]
