[package]
name = "malwaredb"
version = "0.0.2"
edition = "2021"
license = "Apache-2.0"
authors = ["Richard Zak <richard.j.zak@gmail.com>"]
description = "MalwareDB does the bookkeeping for malware & goodware datasets, aimed at helping malware researchers and forensic investigators."
homepage = "https://malwaredb.net/"
repository = "https://github.com/malwaredb/malwaredb-rs"
keywords = ["malware", "malware-research", "forensics"]
categories = ["database", "data-structures", "parsing"]
build = "src/build.rs"

[features]
default = []
sqlite = ["malwaredb-server/sqlite"]
admin = ["dep:dialoguer", "malwaredb-server/admin", "dep:chrono", "dep:hex", "dep:walkdir", "dep:zip"]
admin-gui = ["malwaredb-server/admin", "dep:slint", "dep:slint-build", "dep:drm-sys", "futures/executor"]

[dependencies]
malwaredb-api = { workspace = true }
malwaredb-server = { workspace = true }
malwaredb-types = { workspace = true }

anyhow = { workspace = true }
bytesize = { workspace = true }
chrono = { workspace = true, optional = true }
clap = { workspace = true }
clap_complete = { workspace = true }
dialoguer = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
home = { workspace = true }
serde = { workspace = true }
slint = { workspace = true, optional = true }
tokio = { workspace = true, features = ["rt", "macros"] }
toml = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true, optional = true }
zip = { workspace = true, optional = true }
zeroize = { workspace = true }

[target.'cfg(not(target_os = "wasi"))'.dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[target.'cfg(all(target_os = "linux", not(target_arch = "x86_64")))'.dependencies]
drm-sys = { workspace = true, features = ["use_bindgen"], optional = true } # Subdependency of Slint for non-x86 targets

[dev-dependencies]
malwaredb-server = { workspace = true, features = ["sqlite"] }

[build-dependencies]
slint-build = { workspace = true, optional = true }

[workspace.dependencies]
# Internal dependencies
malwaredb-api = { path = "crates/api", version = "0.0.2" }
malwaredb-server = { path = "crates/server", version = "0.0.2" }
malwaredb-types = { path = "crates/types", version = "0.0.2" }

# External dependencies
anyhow = { version = "1.0", features = ["std"] }
argon2 = { version = "0.5.2", features = ["alloc", "std"], default-features = false }
axum = { version = "0.6.20", features = ["headers", "http1", "json", "macros", "tokio"], default-features = false }
axum-macros = { version = "0.3.7", default-features = false }
base64 = { version = "0.21.4", default-features = false }
bytesize = {version = "1.3", features = ["serde"], default-features = false }
chrono = { version = "0.4.31", features = ["clock", "serde"], default-features = false }
clap = { version = "4.4", features = ["derive", "help", "std", "usage"], default-features = false }
clap_complete = { version = "4.4", default-features = false }
deadpool-postgres = { version = "0.10.5", features = ["rt_tokio_1"], default-features = false }
dialoguer = { version = "0.10.4", features = ["password"], default-features = false }
drm-sys = { version = "0.4" }
duration-string = { version = "0.3.0", features = ["serde"], default-features = false }
flagset = { version = "0.4.4", default-features = false }
futures = { version = "0.3.28", default-features = false }
fuzzyhash = { version = "0.2.2", default-features = false }
hex = { version = "0.4.3", features = ["alloc", "std"], default-features = false }
home = { version = "0.5.5", default-features = false }
http = { version = "^0.2.9", default-features = false }
humansize = { version = "2.1", default-features = false }
hyper = { version = "0.14.27", features = ["http1", "server"], default-features = false }
malwaredb-lzjd = { version = "0.1.2" }
md-5 = { version = "0.10.5", default-features = false }
pdf = { version = "0.8.1", features = ["cache"], default-features = false }
postgres = { version = "0.19.6", features = ["array-impls", "with-chrono-0_4"], default-features = false }
reqwest = { version = "0.11.20", features = ["blocking", "json", "deflate", "gzip"], default-features = false }
rstest = { version = "0.18.2", default-features = false }
rusqlite = { version = "0.29.0", features = ["bundled"], default-features = false }
serde = { version = "1.0", features = ["derive", "std"], default-features = false }
serde_json = { version = "1.0", features = ["alloc"], default-features = false }
sha1 = { version = "0.10.6", features = ["std"], default-features = false }
sha2 = { version = "0.10.6", features = ["std"], default-features = false }
slint = { version = "1.2.0" }
slint-build = { version = "1.2.0" }
tempdir = { version = "0.3.7", default-features = false }
tlsh-fixed = { version = "0.1.1", default-features = false }
tokio = { version = "1", features = ["rt", "macros"], default-features = false }
toml = { version = "0.7.6", features = ["display", "parse"], default-features = false }
tower = { version = "^0.4.11", features = ["util"], default-features = false }
tracing = { version = "0.1.37", default-features = false }
tracing-subscriber = { version="0.3.17", features = ["env-filter", "json", "fmt"], default-features = false }
uuid = { version = "1.4",  features = ["v4"], default-features = false }
walkdir = { version = "2.4", default-features = false }
zip = { version = "0.6.6" }
zeroize = { version = "1.6", features = ["alloc", "derive"], default-features = false }

[profile.release]
lto = true
strip = "debuginfo"

[[bin]]
name = "mdb_server"
path = "src/main.rs"

[workspace]
resolver = "2"
members = [
    'crates/api',
    'crates/types',
    'crates/server',
    'client',
]
