[package]
name = "malwaredb-api"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Common API endpoints and data types for MalwareDB components."
keywords.workspace = true
categories = ["data-structures"]

[dependencies]
chrono = { workspace = true, features = ["serde"] }
hex = { workspace = true, features = ["alloc"] }
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
zeroize = { workspace = true, features = ["alloc", "derive"] }
