[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
duration-string = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }