[package]
name = "malwaredb-api"
version = "0.0.9"
edition = "2021"
license = "Apache-2.0"
authors = ["Richard Zak <richard.j.zak@gmail.com>"]
description = "Common API endpoints and data types for MalwareDB components."
homepage = "https://malwaredb.net/"
repository = "https://github.com/malwaredb/malwaredb-rs"

[dependencies]
chrono = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
zeroize = { workspace = true }
