[package]
name = "malwaredb-api"
version = "0.0.10-dev"
edition = "2021"
license = "Apache-2.0"
authors = ["Richard Zak <richard.j.zak@gmail.com>"]
description = "Common API endpoints and data types for MalwareDB components."
homepage = "https://malwaredb.net/"
repository = "https://github.com/malwaredb/malwaredb-rs"

[dependencies]
chrono = { workspace = true, features = ["serde"] }
hex = { workspace = true, features = ["alloc"] }
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
zeroize = { workspace = true, features = ["alloc", "derive"] }
