[package]
name = "malwaredb-types"
version = "0.0.3"
edition = "2021"
license = "Apache-2.0"
authors = ["Richard Zak <richard.j.zak@gmail.com>"]
description = "Data types and parsers for MalwareDB."
homepage = "https://malwaredb.net/"
repository = "https://github.com/malwaredb/malwaredb-rs"
categories = ["data-structures", "parsing"]
exclude = ["testdata"]

[features]
default = ["elf", "macho", "office95", "officexml", "pe32", "pdf", "rtf"]
elf = ["dep:flagset"]
macho = []
office95 = []
officexml = ["dep:zip"]
pe32 = ["dep:flagset"]
pef = []
pdf = []
rtf = []

[dependencies]
# External
anyhow = { workspace = true }
chrono = { workspace = true }
flagset = { workspace = true, optional = true }
fuzzyhash = {workspace = true }
hex = { workspace = true }
md-5 = { workspace = true }
pdf = { workspace = true }
tracing = { workspace = true }
zip = { workspace = true, optional = true }

[dev-dependencies]
rstest = { workspace = true }