[package]
name = "types"
version = "0.1.0"
edition = "2021"

[features]
default = ["elf", "macho", "pe32", "pdf"]
elf = ["dep:flagset"]
macho = []
pe32 = ["dep:flagset"]
pef = []
pdf = []

[dependencies]
# External
anyhow = { workspace = true }
chrono = { workspace = true }
flagset = { workspace = true, optional = true }
fuzzyhash = {workspace = true }
hex = { workspace = true }
md-5 = { workspace = true }
pdf = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }