[package]
name = "malwaredb-server"
version = "0.0.9-dev"
edition = "2021"
license = "Apache-2.0"
authors = ["Richard Zak <richard.j.zak@gmail.com>"]
description = "Server data storage logic for MalwareDB."
homepage = "https://malwaredb.net/"
repository = "https://github.com/malwaredb/malwaredb-rs"
build = "build.rs"

[features]
default = []
admin = []
sqlite = ["dep:rusqlite"]
vt = ["dep:malwaredb-virustotal", "rusqlite/chrono", "postgres/with-serde_json-1"]
zlibng = ["flate2/zlib-ng"]

[dependencies]
# Internal dependencies
malwaredb-api = { workspace = true }
malwaredb-types = { workspace = true }
malwaredb-virustotal = { workspace = true, optional = true }

# External
aes-gcm = { workspace = true }
anyhow = { workspace = true }
argon2 = { workspace = true }
axum = { workspace = true }
axum-macros = { workspace = true }
base64 = { workspace = true, features = ["alloc", "std"] }
cart_container = { workspace = true }
chrono = { workspace = true }
chrono-humanize = { workspace = true }
constcat = { workspace = true }
deadpool-postgres = { workspace = true }
flate2 = { workspace = true }
fuzzyhash = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
human-hash = { workspace = true }
humansize = { workspace = true }
magic = { workspace = true }
malwaredb-lzjd = { workspace = true }
md-5 = { workspace = true }
postgres = { workspace = true }
rc4 = { workspace = true }
rusqlite = { workspace = true, optional = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
tlsh-fixed = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
xor-utils = { workspace = true }
zeroize = { workspace = true }

[target.'cfg(not(target_os = "wasi"))'.dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
malwaredb-client = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
rstest = { workspace = true }
rusqlite = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }

[target.'cfg(target_os = "windows")'.build-dependencies]
vcpkg = { workspace = true }

[package.metadata.vcpkg.target]
aarch64-pc-windows-msvc = { triplet = "arm64-windows", dependencies = ["libmagic"] }
x86_64-pc-windows-msvc = { triplet = "x64-windows-static", dependencies = ["libmagic"] }

[package.metadata.docs.rs]
all-features = true
