[package]
name = "server"
version = "0.1.0"
edition = "2021"

[features]
default = []
sqlite = ["dep:rusqlite"]

[dependencies]
# Internal dependencies
api = { workspace = true }

# External
anyhow = { workspace = true }
argon2 = { workspace = true }
chrono = { workspace = true }
postgres = { workspace = true }
rusqlite = { workspace = true, optional = true }
uuid = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
rusqlite = { workspace = true }
