[package]
name = "server"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"

[features]
default = []
admin = []
sqlite = ["dep:rusqlite"]

[dependencies]
# Internal dependencies
api = { workspace = true }
types = { workspace = true }

# External
anyhow = { workspace = true }
argon2 = { workspace = true }
axum = { workspace = true }
axum-macros = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
deadpool-postgres = { workspace = true }
duration-string = { workspace = true }
hex = { workspace = true }
humansize = { workspace = true }
lzjd = { workspace = true }
md-5 = { workspace = true }
postgres = { workspace = true }
rusqlite = { workspace = true, optional = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
ssdeep = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
rusqlite = { workspace = true }
