[package]
name = "malwaredb-server"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
authors = ["Richard Zak <richard.j.zak@gmail.com>"]
description = "Server data storage logic for MalwareDB."
homepage = "https://malwaredb.net/"
repository = "https://github.com/malwaredb/malwaredb-rs"

[features]
default = []
admin = []
sqlite = ["dep:rusqlite"]

[dependencies]
# Internal dependencies
malwaredb-api = { workspace = true }
malwaredb-types = { workspace = true }

# External
anyhow = { workspace = true }
argon2 = { workspace = true }
axum = { workspace = true }
axum-macros = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
deadpool-postgres = { workspace = true }
duration-string = { workspace = true }
hex = { workspace = true }
humansize = { workspace = true }
malwaredb-lzjd = { workspace = true }
md-5 = { workspace = true }
postgres = { workspace = true }
rusqlite = { workspace = true, optional = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
ssdeep = { workspace = true }
tlsh-fixed = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
http = { workspace = true }
hyper = { workspace = true }
rstest = { workspace = true }
rusqlite = { workspace = true }
tempdir = { workspace = true }
tower = { workspace = true }
