on:
  workflow_dispatch:
  schedule:
    - cron: '15 3 * * 4'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
name: cargo-update
permissions:
  contents: write
  pull-requests: write
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        run: rustup show && rustup update
      - name: Update dependencies
        run: |
          git config user.name  'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          cargo update
          git checkout -b chore/cargo-update
          git diff --quiet && git diff --staged --quiet || git commit -am 'chore(deps): cargo update to update dependencies' && \
            git push origin chore/cargo-update && echo "updated=0" >>$GITHUB_OUTPUT
        shell: bash
      - name: Create pull request
        if: steps.update_dependencies.outputs.updated == 0
        run: |
          gh pr create -B main -b "chore(deps): cargo update to update dependencies" \
                               -t "chore(deps): cargo update to update dependencies" -l dependencies
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
