name: Commisery
on:
  workflow_call:
  pull_request:
    types: [edited, opened, synchronize, reopened]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This workflow uses a third-party action.
# The existence of a `permissions` key denies all
# permissions except those explicitly specified.
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443

      - name: Run Commisery
        uses: tomtom-international/commisery-action@80d0c42bb2f89a14df1ada3193b444b9d85995e0 # v3.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          validate-pull-request: false
          validate-pull-request-title-bump: false
