name: Commisery
on:
  workflow_call:
  pull_request:
    types: [edited, opened, synchronize, reopened]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This workflow uses a third-party action.
# The existence of a `permissions` key denies all
# permissions except those explicitly specified.
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443

      - name: Run Commisery
        uses: tomtom-international/commisery-action@98ff47b1e06d88495f253b5b16d149f856abb953 # v3.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          validate-pull-request: false
          validate-pull-request-title-bump: false
