name: Commisery
on:
  workflow_call:
  pull_request:
    types: [edited, opened, synchronize, reopened]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This workflow uses a third-party action.
# The existence of a `permissions` key denies all
# permissions except those explicitly specified.
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Run Commisery
        uses: tomtom-international/commisery-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          validate-pull-request: false
          validate-pull-request-title-bump: false
