name: Coverage
on: [pull_request, push]
permissions:
  contents: read
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            codecov.io:443
            crates.io:443
            github.com:443
            index.crates.io:443
            objects.githubusercontent.com:443
            static.crates.io:443
            static.rust-lang.org:443
            storage.googleapis.com:443
            uploader.codecov.io:443

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@6e2226b90b9a51735a2363fdd379c7545cfd8748 # cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --features=admin,sqlite --workspace --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: false
