name: Coverage
on: [pull_request, push]
permissions:
  contents: read
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            cli.codecov.io:443
            codecov.io:443
            crates.io:443
            github.com:443
            index.crates.io:443
            objects.githubusercontent.com:443
            static.crates.io:443
            static.rust-lang.org:443
            storage.googleapis.com:443
            uploader.codecov.io:443

      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@6e2226b90b9a51735a2363fdd379c7545cfd8748 # cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --features=admin,sqlite --workspace --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@54bcd8715eee62d40e33596ef5e8f0f48dbbccab # v4.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: false
