name: Coverage
on: [ pull_request, push ]
permissions:
  contents: read
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            api.github.com:443
            cli.codecov.io:443
            codecov.io:443
            crates.io:443
            github.com:443
            index.crates.io:443
            kv4gacprodeus2file3.blob.core.windows.net:443
            objects.githubusercontent.com:443
            static.crates.io:443
            static.rust-lang.org:443
            storage.googleapis.com:443
            uploader.codecov.io:443

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@6e2226b90b9a51735a2363fdd379c7545cfd8748 # cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --features=sqlite --workspace --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@125fc84a9a348dbcf27191600683ec096ec9021c # v4.4.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: false
