name: Coverage
on: [ pull_request, push ]
permissions:
  contents: read
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            api.github.com:443
            cli.codecov.io:443
            codecov.io:443
            crates.io:443
            github.com:443
            index.crates.io:443
            kv4gacprodeus2file3.blob.core.windows.net:443
            objects.githubusercontent.com:443
            static.crates.io:443
            static.rust-lang.org:443
            storage.googleapis.com:443
            uploader.codecov.io:443

      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@6e2226b90b9a51735a2363fdd379c7545cfd8748 # cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --features=sqlite --workspace --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: false
