name: Cross
on: [ push, pull_request ]
jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install libmagic
        run: brew install libmagic
      - name: Build client & server
        run: cargo build --workspace --features=admin,sqlite --bin mdb_client --bin mdb_server

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install vcpkg
        run: |
          cargo install cargo-vcpkg
          vcpkg install libmagic
          vcpkg integrate install
      - name: Build client & server
        run: cargo build --workspace --features=admin,sqlite --bin mdb_client --bin mdb_server
        env:
          VCPKGRS_DYNAMIC: 1
