name: Cross
on: [ push, pull_request ]
permissions:
  contents: read
jobs:
  macos-intel:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@55e35ac78132cc31ce174408f40a9676e64aa0e2 # master
      - name: Install libmagic
        run: brew install libmagic
      - name: Build client
        run: cargo build --workspace --bin mdb_client
      - name: Build server
        run: cargo build --features=admin,admin-gui,sqlite --bin mdb_server
      - name: Upload mdb_server
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: mdb_server_darwin_x86_64
          path: target/debug/mdb_server
          retention-days: 5
      - name: Upload mdb_client
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: mdb_client_darwin_x86_64
          path: target/debug/mdb_client
          retention-days: 5

  macos-m1:
    runs-on: [self-hosted, macos, arm64]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: dtolnay/rust-toolchain@78c6b5541adb5849f5d72d15da722aedb26327ca # stable
      - name: Build client
        run: cargo build --workspace --bin mdb_client
      - name: Build server
        run: cargo build --features=admin,admin-gui,sqlite --bin mdb_server
        env:
          LIBRARY_PATH: "/opt/homebrew/lib:/opt/homebrew/opt/libmagic/lib"
      - name: Upload mdb_server
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: mdb_server_darwin_arm64
          path: target/debug/mdb_server
          retention-days: 5
      - name: Upload mdb_client
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: mdb_client_darwin_arm64
          path: target/debug/mdb_client
          retention-days: 5

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@cce3ecf1101850047239b3dea39a835e10ffa9d1 # v1.12
      - name: Install vcpkg
        run: |
          cargo install cargo-vcpkg
          vcpkg install libmagic
          vcpkg integrate install
      - name: Build client
        run: cargo build --workspace --bin mdb_client
      - name: Build server
        run: cargo build --features=admin,admin-gui,sqlite
        env:
          VCPKGRS_DYNAMIC: 1
      - name: Upload mdb_server.exe
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: mdb_server.exe
          path: target/debug/mdb_server.exe
          retention-days: 5
      - name: Upload mdb_client.exe
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: mdb_client.exe
          path: target/debug/mdb_client.exe
          retention-days: 5
