name: Lint
on: [ push, pull_request ]
jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust toolchain
      run: rustup show && rustup update
    - name: cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --features=admin,sqlite -- -D warnings

