name: Lint
on: [ push, pull_request ]
jobs:
  rust:
    name: Cargo clippy & fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust toolchain
      run: rustup show && rustup update
    - name: Install GUI dependencies
      run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev libx11-dev libxkbcommon-dev libfontconfig-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev
    - name: cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --all-features --tests -- -D warnings

  udeps:
    name: Unused dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run cargo-udeps
        uses: aig787/cargo-udeps-action@v1
        with:
          version: 'latest'
          args: '--all-targets'

  audit:
    name: Cargo Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cargo Audit
        run: cargo install cargo-audit

      - name: Run Cargo Audit
        run: cargo audit

  hack:
    name: Cargo Hack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cargo Hack
        uses: taiki-e/install-action@cargo-hack

      - name: Run Cargo Hack
        run: |
          cargo hack check --each-feature --no-dev-deps
          cd crates/types
          cargo hack check --each-feature --no-dev-deps
