name: Release
on:
  push:
    tags:
      - "v*"
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: block
          allowed-endpoints: >
            azure.archive.ubuntu.com:80
            crates.io:443
            esm.ubuntu.com:443
            github.com:443
            index.crates.io:443
            motd.ubuntu.com:443
            ppa.launchpadcontent.net:443
            static.crates.io:443
            static.rust-lang.org:443

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Rust toolchain
        run: |
          rustup target install x86_64-unknown-linux-musl
          sudo apt-get install -y musl musl-dev musl-tools
      - name: Install zlibng
        run: |
          sudo apt-get install build-essential wget
          wget https://github.com/zlib-ng/zlib-ng/archive/refs/tags/2.1.6.tar.gz
          tar -xzf 2.1.6.tar.gz
          cd zlib-ng-2.1.6/
          ./configure
          make
          sudo make install

      - name: Install GUI dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev libx11-dev libxkbcommon-dev libfontconfig-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev
      - name: Build client
        run: cargo build --workspace --features=zlibng --bin mdb_client --target x86_64-unknown-linux-musl --release
      - name: Build server
        run: cargo build --features=admin,admin-gui,sqlite,vt,zlibng --bin mdb_server --target x86_64-unknown-linux-musl --release
      - name: Upload mdb_server
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: mdb_server_linux_x86_64
          path: target/x86_64-unknown-linux-musl/release/mdb_server
          retention-days: 5
      - name: Upload mdb_client
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: mdb_client_linux_x86_64
          path: target/x86_64-unknown-linux-musl/release/mdb_client
          retention-days: 5

  macos-intel:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@55e35ac78132cc31ce174408f40a9676e64aa0e2 # master
      - name: Install libmagic and zlib-ng
        run: brew install libmagic zlib-ng
      - name: Build client
        run: cargo build --workspace --features=zlibng --bin mdb_client --release
      - name: Build server
        run: cargo build --features=admin,admin-gui,sqlite,zlibng --bin mdb_server --release
      - name: Upload mdb_server
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: mdb_server_darwin_x86_64
          path: target/release/mdb_server
          retention-days: 5
      - name: Upload mdb_client
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: mdb_client_darwin_x86_64
          path: target/release/mdb_client
          retention-days: 5

  macos-m1:
    runs-on: [ self-hosted, macos, arm64 ]
    needs: macos-intel
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: dtolnay/rust-toolchain@78c6b5541adb5849f5d72d15da722aedb26327ca # stable
      - name: Build client
        run: cargo build --workspace --features=zlibng --bin mdb_client --release
      - name: Build server
        run: cargo build --features=admin,admin-gui,sqlite,zlibng --bin mdb_server --release
        env:
          LIBRARY_PATH: "/opt/homebrew/lib:/opt/homebrew/opt/libmagic/lib"
      - uses: actions/download-artifact@v4
        with:
          name: mdb_server_darwin_x86_64
      - uses: actions/download-artifact@v4
        with:
          name: mdb_client_darwin_x86_64
      - run: lipo -create ./mdb_server ./target/release/mdb_server -output ./mdb_server_darwin_universal
      - run: lipo -create ./mdb_client ./target/release/mdb_client -output ./mdb_client_darwin_universal
      - name: Upload mdb_server
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: mdb_server_darwin_universal
          path: mdb_server_darwin_universal
          retention-days: 5
      - name: Upload mdb_client
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: mdb_client_darwin_universal
          path: mdb_client_darwin_universal
          retention-days: 5

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@cce3ecf1101850047239b3dea39a835e10ffa9d1 # v1.12
      - name: Install vcpkg
        run: |
          cargo install cargo-vcpkg
          vcpkg install libmagic
          vcpkg install zlib-ng
          vcpkg integrate install
      - name: Build client
        run: cargo build --workspace --features=zlibng --bin mdb_client --release
      - name: Build server
        run: cargo build --features=admin,admin-gui,sqlite,vt,zlibng --release
        env:
          VCPKGRS_DYNAMIC: 1
      - name: Upload mdb_server.exe
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: mdb_server.exe
          path: target/release/mdb_server.exe
          retention-days: 5
      - name: Upload mdb_client.exe
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: mdb_client.exe
          path: target/release/mdb_client.exe
          retention-days: 5