name: Generate the CycloneDX BOM

on: [workflow_dispatch, workflow_call]
permissions:
  contents: read

jobs:
  Generate-BOM-Manifest:
    name: Run cargo-cyclonedx and generate BOM files [both JSON and XML]
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: block
          allowed-endpoints: >
            azure.archive.ubuntu.com:80
            crates.io:443
            esm.ubuntu.com:443
            github.com:443
            index.crates.io:443
            motd.ubuntu.com:443
            packages.microsoft.com:443
            ppa.launchpadcontent.net:443
            static.crates.io:443
            static.rust-lang.org:443

      - run: |
          sudo apt -o Acquire::Retries=3 update
          sudo apt -o Acquire::Retries=3 install -y musl-tools musl-dev

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install Rust tool chain
        uses: dtolnay/rust-toolchain@78c6b5541adb5849f5d72d15da722aedb26327ca # stable
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - name: Install cargo-cyclonedx
        run: cargo install cargo-cyclonedx

      - name: Run cycloneDX and get JSON output
        run: cargo cyclonedx --all --format=json

      - name: Run cycloneDX and get XML output
        run: cargo cyclonedx --all --format=xml

      - name: Upload the JSON BOM file
        uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
        with:
          name: SBOM.json
          path: bom.json

      - name: Upload the XML BOM file
        uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
        with:
          name: SBOM.xml
          path: bom.xml
