name: Regenerate and upload CycloneDX Manifest on changes to Cargo.lock file

on:
  push:
    paths:
      - Cargo.lock
permissions:
  contents: read

jobs:
  Regenerate-BOM:
    uses: ./.github/workflows/sbom_manifest_action.yml
