name: Test
on: [ push, pull_request ]
jobs:
  native:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust toolchain
      run: rustup show
    - name: Build client & server
      run: cargo build --workspace --all-features
    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace --all-features
